name: nuid
version: 0.7.0
description: >
  A Dart-lang implementation of NATS Unique Identifiers
author: Frank Moreno <frankmoreno1993@gmail.com>
homepage: http://www.github.com/kranfix/dart-nuid
documentation: http://www.github.com/kranfix/dart-nuid#readme
