name: nuid
version: 0.7.2
description: >
  A Dart implementation of NATS (nats.io) Unique Identifiers (uid) inspired by
  github.com/nats-io/node-nuid.
author: Frank Moreno <frankmoreno1993@gmail.com>
homepage: https://www.github.com/kranfix/dart-nuid
documentation: https://www.github.com/kranfix/dart-nuid#readme
environment:
  sdk: ">=2.0.0 <3.0.0"
