name: nuid
version: 2.0.0
description: >
  A Dart implementation of NATS (nats.io) Unique Identifiers (uid) inspired by
  github.com/nats-io/node-nuid.
homepage: https://www.github.com/kranfix/dart-nuid
repository: https://www.github.com/kranfix/dart-nuid#readme
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
  very_good_analysis: ^2.0.0
